### ISSUE TITLE
[PD] Watch Power Pose TED talk

### ISSUE THREAD

**Issue by wainwmr** [CodeYourFuture/Module-JS2#43]
### Coursework content

Your body language may shape who you are.

Watch this [TED Talk by Amy Cuddy](https://www.ted.com/talks/amy_cuddy_your_body_language_may_shape_who_you_are), a social psychologist, on non-verbal communication.

Note: some of the findings described in this video have caused much debate.  However, more [recent science](https://www.bps.org.uk/psychologist/decade-power-posing-where-do-we-stand) still suggests that your posture does affect your own experienced feelings of power, although it may be sufficient to mindfully avoid the negative ‘contractive’ postures.

### Estimated time in hours

0.5

### What is the purpose of this assignment?

Understand how your own body language can affect not only the way that other people see you, but also how you feel yourself.

**Comment by kfklein15** [comment]
This will no longer be used in our coursework.
